// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWg1dtx2CrEm4_-YAhz_lgoTOt1H6pfk',
    appId: '1:74965085957:web:c9b558ed31c630eb13516c',
    messagingSenderId: '74965085957',
    projectId: 'notenrechner-7e934',
    authDomain: 'notenrechner-7e934.firebaseapp.com',
    storageBucket: 'notenrechner-7e934.appspot.com',
    measurementId: 'G-9WKN0R81V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBq-5drBS7a1qjjUhasO3D19Epk4E4zLE',
    appId: '1:74965085957:android:91be305eb5e2461913516c',
    messagingSenderId: '74965085957',
    projectId: 'notenrechner-7e934',
    storageBucket: 'notenrechner-7e934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLEuKPA4LlkEIFsGpduE7clXJ8-1C4hxw',
    appId: '1:74965085957:ios:d40885ea04a1d19413516c',
    messagingSenderId: '74965085957',
    projectId: 'notenrechner-7e934',
    storageBucket: 'notenrechner-7e934.appspot.com',
    iosClientId: '74965085957-jqnvmik9833pble2ltaqfenecof8ir88.apps.googleusercontent.com',
    iosBundleId: 'ch.bbbaden.program',
  );
}
